apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- frontend-deployment.yaml
- frontend-service.yaml
namespace: frontend
images:
- name: frontend
  newName: leui/tcc-frontend-prod
  newTag: 576184a8ed2c34da331d4f5f16bd320c1715fc9b
