name: CI/CD

on:
  push:
    branches:
      - main
      - develop
      - frontend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push dev image
        run: |
          docker build -t leui/tcc-frontend:${{ github.sha }} .
          docker push leui/tcc-frontend:${{ github.sha }}

      - name: Build and push prod image
        run: |
          docker build -f Dockerfile.prod -t leui/tcc-frontend-prod:${{ github.sha }} .
          docker push leui/tcc-frontend-prod:${{ github.sha }}
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Install kustomize
        run: |
          curl -LO https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v4.5.7/kustomize_v4.5.7_linux_amd64.tar.gz
          tar -xvzf kustomize_v4.5.7_linux_amd64.tar.gz
          sudo mv kustomize /usr/local/bin/
          kustomize version

      - name: update kubernetes
        run: |
          cd k8s
          kustomize edit set image frontend=leui/tcc-frontend-prod:${{ github.sha }}
          cat kustomization.yaml

      - name: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Deploy Action"
          git commit -am "image update done by kustomization"

      - name: push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          branch: frontend
