name: CI/CD

on:
  push:
    branches:
      - main
      - develop
      - frontend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push dev image
        run: |
          docker build -t leui/tcc-frontend .
          docker push leui/tcc-frontend

      - name: Build and push prod image
        run: |
          docker build -f Dockerfile.prod -t leui/tcc-frontend-prod .
          docker push leui/tcc-frontend-prod
